version: '3.7'

services:
  dulam-farms:
    container_name: dulam-farms
    build: 
      context: .
      dockerfile: Dockerfile

    volumes: 
      - './:app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true