version: 2.1
jobs:
  build-lambda:
    working_directory: ~/dulam-farms
    docker:
      - image: circleci/golang:1.14
    environment: # environment variables for the build itself
      GO111MODULE: "on"
      GOBIN: $(readlink -e ./.lambda)
    steps:
      - checkout
      - run: mkdir -p .lambda
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: go build -o ./.lambda -i ./go-src

  build-client:
    working_directory: ~/dulam-farms
    docker:
      - image: circleci/node:10.21.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build client
          command: yarn build:client
#      - run:
#          name: build lambda function
#          command: GOBIN=$(pwd)/.lambda go install ./...
      - store_artifacts:
          path: ./build

workflows:
  version: 2
  build-workflow:
    jobs:
      - build-lambda
      - build-client