version: 2.1
jobs:
  build:
    working_directory: ~/dulam-farms
    docker:
      - image: circleci/node:10.21.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build client
          command: yarn build:client
      - run:
          name: build lambda function
          command: yarn build:lambda

      - store_artifacts:
          path: ./build
